language: perl
perl: 
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"

install:
    - bin/install_dev_configs
    - bin/update_dev_configs

notifications:
    recipients:
        - c@frederico.me
    email:
        on_success: change
        on_failure: always

