#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;

use Cwd;
use File::Copy;
use File::Path qw< make_path >;

my $dot_vimrc = $ENV{ HOME } . "/.vimrc";
my $dot_vim_path = $ENV{ HOME } . "/.vim";
my $dot_vim_colors = $dot_vim_path . "/colors";
my $dot_plugin_git = $dot_vim_path . "/git";

my @vim_plugins = (
    'https://github.com/fholgado/minibufexpl.vim.git',
    'https://github.com/fredericorecsky/vonque-shell.git',
    'https://github.com/fredericorecsky/vonque-colors.git',
);

sub vimrc_bootstrap {
    if ( -e $dot_vimrc ) {
        copy ( $dot_vimrc, $dot_vimrc. ".vc_bck" )
            or die "There is a .vimrc file and was not possible make a backup. $!\n";
    }

    print "Creating a new .vim config file\n";
    open my $fh, ">", $dot_vimrc;
        print $fh <DATA>;
    close $fh;
}

sub vim_directory_bootstrap {
    make_path ( $dot_vim_path, $dot_plugin_git, $dot_vim_colors );
    chdir ( $dot_plugin_git );
    for my $plugin ( @vim_plugins ) {
        #todo check errors
        my $cmd = `git clone $plugin`;
    }
    opendir my $dh, $dot_plugin_git 
        or die "Could not read plugins from directory $dot_plugin_git\n $!\n";
    my @directories = grep { !/^\./ } readdir ( $dh );
    close $dh;
    for my $directory ( @directories ) {
        print "installing $directory...\n";
        chdir( $dot_plugin_git . "/". $directory );
        # easy way
        my $cmd = `cp -a * $dot_vim_path`;
    }
}

print "Vim Config will configure your vim editor..\n";
vim_directory_bootstrap;
vimrc_bootstrap;


__DATA__
set wrap
set tabstop=4
set autoindent
set softtabstop=4
set expandtab
set shiftwidth=4
set wildchar=<F8>
set number
set bg=light
set list
syntax on
colorscheme ashen
