#!/bin/sh

if [ -n "$DEBUG" ]; then 
    echo "debugging on $DEBUG"
    alias debug_message="echo"
else
    #echo "debugging off $DEBUG"
    alias debug_message="true "
fi

# If not running interactively, don't do anything
case $- in
    *i*)   debug_message "This shell is interactive";;
    *)  debug_message "This shell is not interactive" ;;
esac

platform='unknown'
unamestr=`uname`
if [ "$unamestr" == 'Linux' ]; then
   platform='linux'
elif [ "$unamestr" == 'Darwin' ]; then
      platform='Darwin'
fi

filename="$HOME/.bashrc"
if [ $platform == 'Darwin' ]; then
    filename="$HOME/.profile"
fi

if [ ! -e $filename ];then
    echo "No configuration was found, installing myself on $filename"
    echo "$0 -> $filename"
    mydir=`pwd`/$0
    ln -s $mydir $filename
else
    debug_message "Configuration file already exists"
fi

export GITHUB=~/github

for configuration in $GITHUB/configs/bashrc/*_*;
do 
    if [ -f $configuration ];then
        debug_message "Processing $configuration"
        . $configuration
    fi
done

# Copy my versions of .vimrc over

pushd . &>/dev/null
cd  
for vim in $GITHUB/configs/vim/.v*;
do 
    file=`basename $vim`
    if ! [[ -L $file ]]; then
        if [ -e $file ]; then
            rm $file
            ln -s $vim .
        else 
            ln -s $vim .
        fi
    fi
done
popd  &>/dev/null
